In [1]:
print("hello numpy")

hello numpy


In [2]:
import numpy as np

ar1 = np.array([1,2,4,3,5])
print(type(ar1))

<class 'numpy.ndarray'>


In [3]:
ar2 = np.array([
    [1,2,3],
    [4,5,6]
])
ar2

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
ar2.ndim

2

In [5]:
ar3 = np.array([
    # 1st floor
   [[1,2,3],
    [4,5,6]],

    # 2nd floor
     [[1,2,3],
    [4,5,6]]
])

ar3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [6]:
ar3.ndim

3

In [7]:
arr = np.array([1,2,3,4], dtype=np.float64)

arr

array([1., 2., 3., 4.])

In [8]:
arr = np.array([1,2,3,4, "hello"], dtype=np.float64)
arr

ValueError: could not convert string to float: 'hello'

In [ ]:
arr = np.array([1,2,3,4], dtype=np.float64)

arr = arr.astype(np.int64)

arr

In [ ]:
mixed_lst = [10, True, "hello", 10.5]

arr = np.array(mixed_lst, dtype=np.int32)


In [ ]:
# list
lst = [23, 42, 12, 32]

arr = np.array(lst, dtype=np.float32)
arr

In [ ]:
# tuple
tup = (23, 42, 12, 32)

arr = np.array(tup, dtype=np.float32)
arr


In [ ]:
# set 
s = {23, 42, 12, 32}

arr = np.array(list(s), dtype=np.int32)
arr


In [ ]:
# dictionary
dc = {'a': 10, 'b':32, 'c':75}

keys = dc.keys()
values = dc.values()

In [11]:
arr = np.random.rand(2,3)
print(arr)
print(arr.ndim)
print(arr.dtype)
print(arr.shape)
print(arr.size)

[[0.03751662 0.12596307 0.66807717]
 [0.55092695 0.0115951  0.75214213]]
2
float64
(2, 3)
6


In [17]:
arr = np.random.randint(1, 10, (2,3))
print(arr)
print(arr.ndim)
print(arr.dtype)
print(arr.shape)
print(arr.size)

[[5 3 3]
 [6 9 3]]
2
int32
(2, 3)
6


In [20]:
arr = np.random.uniform(50, 100, (3,4))
print(arr)
print(arr.ndim)
print(arr.dtype)
print(arr.shape)
print(arr.size)

[[52.99060641 88.17744033 71.76418762 83.08559306]
 [73.03432986 96.42319423 68.21891827 50.70086829]
 [64.6132434  73.5242889  66.6237041  93.49360637]]
2
float64
(3, 4)
12


In [23]:
arr = np.arange(1, 10, 1)
arr = arr.reshape(3,3)
print(arr)
print(arr.ndim)
print(arr.dtype)
print(arr.shape)
print(arr.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
int64
(3, 3)
9


In [25]:

arr = np.linspace(1, 10, 10)

print(arr)
print(arr.ndim)
print(arr.dtype)
print(arr.shape)
print(arr.size)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
1
float64
(10,)
10


In [28]:

arr = np.logspace(0, 4, 5, base=2)

print(arr)

[ 1.  2.  4.  8. 16.]


In [29]:
a = np.linspace(0,10,5)
a

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [30]:
arr = np.full((2,2), np.inf)
arr

array([[inf, inf],
       [inf, inf]])

In [31]:
arr = np.array([[10,20,30],[40,50,60]])

arr[:,1]

array([20, 50])

In [ ]:
ar = np.array([1,2,3,4,5])
ar[1:4]=0
ar