In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1, 100, size=(10,5))

In [3]:
arr

array([[31, 78, 48, 47, 38],
       [78, 52, 16, 32, 59],
       [40,  8, 55, 68, 68],
       [19, 72, 76, 39, 80],
       [29, 31, 15, 30,  3],
       [74, 37, 22, 12, 27],
       [33,  8, 87, 41, 27],
       [39, 87, 68,  7, 53],
       [50, 14, 21, 73, 96],
       [33,  1, 95, 91,  8]], dtype=int32)

In [4]:
arr= arr.reshape(5, 10)
arr

array([[31, 78, 48, 47, 38, 78, 52, 16, 32, 59],
       [40,  8, 55, 68, 68, 19, 72, 76, 39, 80],
       [29, 31, 15, 30,  3, 74, 37, 22, 12, 27],
       [33,  8, 87, 41, 27, 39, 87, 68,  7, 53],
       [50, 14, 21, 73, 96, 33,  1, 95, 91,  8]], dtype=int32)

In [5]:
flatten = arr.flatten()
flatten.ndim
print(flatten)

[31 78 48 47 38 78 52 16 32 59 40  8 55 68 68 19 72 76 39 80 29 31 15 30
  3 74 37 22 12 27 33  8 87 41 27 39 87 68  7 53 50 14 21 73 96 33  1 95
 91  8]


In [6]:
a= np.random.randint(1, 10, size=(2,3))
b= np.random.randint(20, 30, size=(2,3))

In [7]:
a

array([[6, 8, 4],
       [8, 2, 2]], dtype=int32)

In [8]:
b

array([[21, 26, 29],
       [25, 20, 27]], dtype=int32)

In [9]:
con = np.concatenate((a,b), axis=0)
print(con)

con = np.concatenate((a,b), axis=1)
print(con)

[[ 6  8  4]
 [ 8  2  2]
 [21 26 29]
 [25 20 27]]
[[ 6  8  4 21 26 29]
 [ 8  2  2 25 20 27]]


In [10]:
mat = np.array([
    [10, 20, 30],
    [30, 40, 50]
])

In [11]:
transpose = mat.T
transpose

array([[10, 30],
       [20, 40],
       [30, 50]])

In [13]:
# inplace sorting

x = np.array([10, 8, 16, 100])
z = x.copy()

print(z)

z.sort()
print(z)



[ 10   8  16 100]
[  8  10  16 100]


In [14]:
# copy sorting

print(x)
sort_arr = np.sort(x)
print(sort_arr)

print(x)


[ 10   8  16 100]
[  8  10  16 100]
[ 10   8  16 100]


In [15]:
# 2d array
mat = np.array([[10, 4, 7], [6, 3, 9]])

# horizon, axix=1
hor_sort = np.sort(mat, axis=1)
print(hor_sort)


[[ 4  7 10]
 [ 3  6  9]]


In [16]:
# vertical, axix=0
ver_sort = np.sort(mat, axis=0)
print(ver_sort)


[[ 6  3  7]
 [10  4  9]]


In [17]:
# np.where (condition, x, y) if true x, otherwiae replace with y
x = np.array([10, 8, 16, 100])
print(x)


index = np.where(x==16)
print(index)


[ 10   8  16 100]
(array([2]),)


In [20]:
index = np.where(x>10)
print(index)


(array([2, 3]),)


In [21]:
x = np.array([10, 100, 8, 16, 100])

maximum_value_index = np.argmax(x)
minimum_value_index = np.argmin(x)

print(maximum_value_index)
print(minimum_value_index)



1
2


In [22]:
# counting in array
a = np.random.randint(1, 100, size=(100,))
print(a)

[23 16 14 65 16 92 35  6 70 90 11 32 26 98 74 76 58 17 14  4 14 54 40 50
 79 26 70 18 48 28 20 79 74 31 16 71 27 67 83 38 78 63 22  1 16 13 92 56
 87 30 18 73 38 60 75 47 42 50 46 40 70 66 18 89 51  6 31 32 48 88 76 10
 76 83 79 50 19 98 46 84 30 68 16 10 75 49 69 64 11  7 76  9 41 73 50 25
 74 48 20 48]


In [23]:
value_greater_than_60 = np.count_nonzero(a>70)

print(value_greater_than_60)

27


In [24]:
unique_value, count = np.unique(a, return_counts=True)
print(unique_value, count)

[ 1  4  6  7  9 10 11 13 14 16 17 18 19 20 22 23 25 26 27 28 30 31 32 35
 38 40 41 42 46 47 48 49 50 51 54 56 58 60 63 64 65 66 67 68 69 70 71 73
 74 75 76 78 79 83 84 87 88 89 90 92 98] [1 1 2 1 1 2 2 1 3 5 1 3 1 2 1 1 1 2 1 1 2 2 2 1 2 2 1 1 2 1 4 1 4 1 1 1 1
 1 1 1 1 1 1 1 1 3 1 2 3 2 4 1 3 2 1 1 1 1 1 2 2]
