In [3]:
import numpy as np

In [4]:
arr = np.random.randint(1, 100, size=(10,5))

In [5]:
arr

array([[70, 55, 42, 48, 30],
       [94, 66, 22, 38, 29],
       [67, 91, 62, 80, 91],
       [96, 86, 72, 49, 92],
       [98, 97, 13, 18, 82],
       [ 5, 17,  9, 15, 79],
       [64,  3, 18, 58, 72],
       [20, 52,  2, 49, 81],
       [40, 51, 15, 75, 98],
       [81, 96, 51, 89, 69]], dtype=int32)

In [6]:
arr= arr.reshape(5, 10)
arr

array([[70, 55, 42, 48, 30, 94, 66, 22, 38, 29],
       [67, 91, 62, 80, 91, 96, 86, 72, 49, 92],
       [98, 97, 13, 18, 82,  5, 17,  9, 15, 79],
       [64,  3, 18, 58, 72, 20, 52,  2, 49, 81],
       [40, 51, 15, 75, 98, 81, 96, 51, 89, 69]], dtype=int32)

In [7]:
flatten = arr.flatten()
flatten.ndim
print(flatten)

[70 55 42 48 30 94 66 22 38 29 67 91 62 80 91 96 86 72 49 92 98 97 13 18
 82  5 17  9 15 79 64  3 18 58 72 20 52  2 49 81 40 51 15 75 98 81 96 51
 89 69]


In [8]:
a= np.random.randint(1, 10, size=(2,3))
b= np.random.randint(20, 30, size=(2,3))

In [9]:
a

array([[2, 8, 3],
       [8, 1, 7]], dtype=int32)

In [10]:
b

array([[28, 21, 21],
       [28, 29, 26]], dtype=int32)

In [11]:
con = np.concatenate((a,b), axis=0)
print(con)

con = np.concatenate((a,b), axis=1)
print(con)

[[ 2  8  3]
 [ 8  1  7]
 [28 21 21]
 [28 29 26]]
[[ 2  8  3 28 21 21]
 [ 8  1  7 28 29 26]]


In [12]:
mat = np.array([
    [10, 20, 30],
    [30, 40, 50]
])

In [13]:
transpose = mat.T
transpose

array([[10, 30],
       [20, 40],
       [30, 50]])

In [14]:
# inplace sorting

x = np.array([10, 8, 16, 100])
z = x.copy()

print(z)

z.sort()
print(z)



[ 10   8  16 100]
[  8  10  16 100]


In [15]:
# copy sorting

print(x)
sort_arr = np.sort(x)
print(sort_arr)

print(x)


[ 10   8  16 100]
[  8  10  16 100]
[ 10   8  16 100]


In [16]:
# 2d array
mat = np.array([[10, 4, 7], [6, 3, 9]])

# horizon, axix=1
hor_sort = np.sort(mat, axis=1)
print(hor_sort)


[[ 4  7 10]
 [ 3  6  9]]


In [17]:
# vertical, axix=0
ver_sort = np.sort(mat, axis=0)
print(ver_sort)


[[ 6  3  7]
 [10  4  9]]


In [18]:
# np.where (condition, x, y) if true x, otherwiae replace with y
x = np.array([10, 8, 16, 100])
print(x)


index = np.where(x==16)
print(index)


[ 10   8  16 100]
(array([2]),)


In [19]:
index = np.where(x>10)
print(index)


(array([2, 3]),)


In [20]:
x = np.array([10, 100, 8, 16, 100])

maximum_value_index = np.argmax(x)
minimum_value_index = np.argmin(x)

print(maximum_value_index)
print(minimum_value_index)



1
2


In [21]:
# counting in array
a = np.random.randint(1, 100, size=(100,))
print(a)

[18 90 88 26  2 66 81 81 10  9 86 65 35 99 75 62  9 36 96 95 18  5 19 69
 30 83 53 62 74 27 39 73 52 66 84 12 82 67 49 77 43 16 80 43 82 60 53  8
 69 59 93 65 28 43 93 81 82 21 34 72 37 87 88 41 33 88 87 65 77 41 41 41
 12 80 75 89 19 31 59 48 60  2 16 73  6 14 43 65  2 84  2  4 43 13  1 11
  8 64 68 42]


In [22]:
value_greater_than_60 = np.count_nonzero(a>70)

print(value_greater_than_60)

32


In [23]:
unique_value, count = np.unique(a, return_counts=True)
print(unique_value, count)

[ 1  2  4  5  6  8  9 10 11 12 13 14 16 18 19 21 26 27 28 30 31 33 34 35
 36 37 39 41 42 43 48 49 52 53 59 60 62 64 65 66 67 68 69 72 73 74 75 77
 80 81 82 83 84 86 87 88 89 90 93 95 96 99] [1 4 1 1 1 2 2 1 1 2 1 1 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1 4 1 5 1 1 1 2 2 2 2
 1 4 2 1 1 2 1 2 1 2 2 2 3 3 1 2 1 2 3 1 1 2 1 1 1]


## Bonus

ndarray from scratch

In [24]:
import numpy as np

# zeros array

arr = np.zeros((2, 3))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)


[[0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6


In [32]:
arr3 = np.zeros((2, 3, 3))
print(arr3)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [33]:
arr = np.zeros_like(arr3)

print(arr)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [35]:

arr2 = np.ones((4, 3))

print(arr2)
print(type(arr))
print(arr2.dtype)
print(arr2.shape)
print(arr2.ndim)
print(arr2.size)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
<class 'numpy.ndarray'>
float64
(4, 3)
2
12
